package aplicacion.modelo.dominio;
// Generated 14-jun-2017 18:20:34 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.User;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agentes generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private int legajo;
     private User user;
     private String tipoNroDoc;
     private String nroMatricula;
     private String dm;
     private Date fechaNac;
     private char sexo;
     private String estadoCivil;
     private int numCuitCuil;
     private String apellido;
     private String apellidoCasada;
     private String nombre;
     private String ocupacion;
     private String titulo;
     private String provincia;
     private int codPostal;
     private String localidad;
     private String barrio;
     private String calle;
     private int numCalle;
     private String telefono;
     private String mail;
     private boolean estado;
     private Set cargosDeclaradoses = new HashSet(0);

    public Agente() {
    }

	
    public Agente(int legajo, User user, String tipoNroDoc, String nroMatricula, Date fechaNac, char sexo, String estadoCivil, int numCuitCuil, String apellido, String nombre, String ocupacion, String titulo, String provincia, int codPostal, String localidad, String calle, int numCalle, String telefono, String mail, boolean estado) {
        this.legajo = legajo;
        this.user = user;
        this.tipoNroDoc = tipoNroDoc;
        this.nroMatricula = nroMatricula;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.estadoCivil = estadoCivil;
        this.numCuitCuil = numCuitCuil;
        this.apellido = apellido;
        this.nombre = nombre;
        this.ocupacion = ocupacion;
        this.titulo = titulo;
        this.provincia = provincia;
        this.codPostal = codPostal;
        this.localidad = localidad;
        this.calle = calle;
        this.numCalle = numCalle;
        this.telefono = telefono;
        this.mail = mail;
        this.estado = estado;
    }
    public Agente(int legajo, User user, String tipoNroDoc, String nroMatricula, String dm, Date fechaNac, char sexo, String estadoCivil, int numCuitCuil, String apellido, String apellidoCasada, String nombre, String ocupacion, String titulo, String provincia, int codPostal, String localidad, String barrio, String calle, int numCalle, String telefono, String mail, boolean estado, Set cargosDeclaradoses) {
       this.legajo = legajo;
       this.user = user;
       this.tipoNroDoc = tipoNroDoc;
       this.nroMatricula = nroMatricula;
       this.dm = dm;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.numCuitCuil = numCuitCuil;
       this.apellido = apellido;
       this.apellidoCasada = apellidoCasada;
       this.nombre = nombre;
       this.ocupacion = ocupacion;
       this.titulo = titulo;
       this.provincia = provincia;
       this.codPostal = codPostal;
       this.localidad = localidad;
       this.barrio = barrio;
       this.calle = calle;
       this.numCalle = numCalle;
       this.telefono = telefono;
       this.mail = mail;
       this.estado = estado;
       this.cargosDeclaradoses = cargosDeclaradoses;
    }
   
    public int getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTipoNroDoc() {
        return this.tipoNroDoc;
    }
    
    public void setTipoNroDoc(String tipoNroDoc) {
        this.tipoNroDoc = tipoNroDoc;
    }
    public String getNroMatricula() {
        return this.nroMatricula;
    }
    
    public void setNroMatricula(String nroMatricula) {
        this.nroMatricula = nroMatricula;
    }
    public String getDm() {
        return this.dm;
    }
    
    public void setDm(String dm) {
        this.dm = dm;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public int getNumCuitCuil() {
        return this.numCuitCuil;
    }
    
    public void setNumCuitCuil(int numCuitCuil) {
        this.numCuitCuil = numCuitCuil;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getApellidoCasada() {
        return this.apellidoCasada;
    }
    
    public void setApellidoCasada(String apellidoCasada) {
        this.apellidoCasada = apellidoCasada;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public int getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(int codPostal) {
        this.codPostal = codPostal;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumCalle() {
        return this.numCalle;
    }
    
    public void setNumCalle(int numCalle) {
        this.numCalle = numCalle;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getCargosDeclaradoses() {
        return this.cargosDeclaradoses;
    }
    
    public void setCargosDeclaradoses(Set cargosDeclaradoses) {
        this.cargosDeclaradoses = cargosDeclaradoses;
    }




}


