package aplicacion.modelo.dominio;
// Generated 14-jun-2017 18:20:34 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.Funcion;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CargosDeclarados generated by hbm2java
 */
public class CargoDeclarado  implements java.io.Serializable {


     private int codigo;
     private Agente agente;
     private Funcion funcion;
     private String dependencia;
     private String imputacion;
     private String calle;
     private int numCalle;
     private String localidad;
     private String provincia;
     private Date fechaIngreso;
     private String estadoCargo;
     private boolean estado;
     private String lugar;
     private Date fecha;
     private Set horarioses = new HashSet(0);

    public CargoDeclarado() {
    }

	
    public CargoDeclarado(int codigo, Agente agente, Funcion funcion, String dependencia, String imputacion, String calle, int numCalle, String localidad, String provincia, Date fechaIngreso, String estadoCargo, boolean estado, String lugar, Date fecha) {
        this.codigo = codigo;
        this.agente = agente;
        this.funcion = funcion;
        this.dependencia = dependencia;
        this.imputacion = imputacion;
        this.calle = calle;
        this.numCalle = numCalle;
        this.localidad = localidad;
        this.provincia = provincia;
        this.fechaIngreso = fechaIngreso;
        this.estadoCargo = estadoCargo;
        this.estado = estado;
        this.lugar = lugar;
        this.fecha = fecha;
    }
    public CargoDeclarado(int codigo, Agente agente, Funcion funcion, String dependencia, String imputacion, String calle, int numCalle, String localidad, String provincia, Date fechaIngreso, String estadoCargo, boolean estado, String lugar, Date fecha, Set horarioses) {
       this.codigo = codigo;
       this.agente = agente;
       this.funcion = funcion;
       this.dependencia = dependencia;
       this.imputacion = imputacion;
       this.calle = calle;
       this.numCalle = numCalle;
       this.localidad = localidad;
       this.provincia = provincia;
       this.fechaIngreso = fechaIngreso;
       this.estadoCargo = estadoCargo;
       this.estado = estado;
       this.lugar = lugar;
       this.fecha = fecha;
       this.horarioses = horarioses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Agente getAgente() {
        return this.agente;
    }
    
    public void setAgente(Agente agente) {
        this.agente = agente;
    }
    public Funcion getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(Funcion funcion) {
        this.funcion = funcion;
    }
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }
    public String getImputacion() {
        return this.imputacion;
    }
    
    public void setImputacion(String imputacion) {
        this.imputacion = imputacion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumCalle() {
        return this.numCalle;
    }
    
    public void setNumCalle(int numCalle) {
        this.numCalle = numCalle;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getEstadoCargo() {
        return this.estadoCargo;
    }
    
    public void setEstadoCargo(String estadoCargo) {
        this.estadoCargo = estadoCargo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set horarioses) {
        this.horarioses = horarioses;
    }




}


