package aplicacion.modelo.dominio;
// Generated 14-jun-2017 18:20:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funciones generated by hbm2java
 */
public class Funcion  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private int cargaHoraria;
     private Set cargosDeclaradoses = new HashSet(0);

    public Funcion() {
    }

	
    public Funcion(int codigo, String nombre, int cargaHoraria) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.cargaHoraria = cargaHoraria;
    }
    public Funcion(int codigo, String nombre, int cargaHoraria, Set cargosDeclaradoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.cargaHoraria = cargaHoraria;
       this.cargosDeclaradoses = cargosDeclaradoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(int cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Set getCargosDeclaradoses() {
        return this.cargosDeclaradoses;
    }
    
    public void setCargosDeclaradoses(Set cargosDeclaradoses) {
        this.cargosDeclaradoses = cargosDeclaradoses;
    }




}


