package aplicacion.modelo.dominio;
// Generated 14-jun-2017 18:20:34 by Hibernate Tools 4.3.1




/**
 * Horarios generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private int codigo;
     private CargoDeclarado cargoDeclarado;
     private String dia;
     private double desde;
     private double hasta;
     private boolean estado;

    public Horario() {
    }

    public Horario(int codigo, CargoDeclarado cargoDeclarado, String dia, double desde, double hasta, boolean estado) {
       this.codigo = codigo;
       this.cargoDeclarado = cargoDeclarado;
       this.dia = dia;
       this.desde = desde;
       this.hasta = hasta;
       this.estado = estado;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public CargoDeclarado getCargoDeclarado() {
        return this.cargoDeclarado;
    }
    
    public void setCargoDeclarado(CargoDeclarado cargoDeclarado) {
        this.cargoDeclarado = cargoDeclarado;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public double getDesde() {
        return this.desde;
    }
    
    public void setDesde(double desde) {
        this.desde = desde;
    }
    public double getHasta() {
        return this.hasta;
    }
    
    public void setHasta(double hasta) {
        this.hasta = hasta;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


