package aplicacion.modelo.dominio;
// Generated 10-jun-2017 17:16:50 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String lastname;
     private char sex;
     private String tel;

    public User() {
    }

	
    public User(String username, String password, String name, String lastname, char sex) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.lastname = lastname;
        this.sex = sex;
    }
    public User(String username, String password, String name, String lastname, char sex, String tel) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.lastname = lastname;
       this.sex = sex;
       this.tel = tel;
    }

    public User(String ejemplo1, String string, String ejemplo10, String ejemplo11, char c, int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


